@startuml
'https://plantuml.com/sequence-diagram

:Cliente:
usecase (Confirmar pedido) as Confirm
usecase (Cancelar pedido) as Cancel
usecase (Devolver pedido) as Return

:Cliente: -- Confirm
:Cliente: -- Cancel
Confirm .> Return: <<include>>
Cancel .> Return: <<include>>
@enduml