@startuml
'https://plantuml.com/sequence-diagram

skinparam handwritten true

skinparam usecase {
BackgroundColor LightGreen
BorderColor Blue

ArrowColor LightBlue
}
usecase c1 as "Sacar dinero
--
+ solicitud hecha"
c1 <.. (Retener tarjeta) : <<extends>



note "Description\n--\ncondición:\n\t{historia sospechosa}\npunto de extensión:\n\tsolicitud hecha" as note1
note1 -- c1




@enduml