@startuml
'https://plantuml.com/sequence-diagram

:New actor: -- (Indentificarse)
:New actor: -- (Pagar)
:New actor: -- (Elegir mensajero)
:New actor: -- (Confirmar)

(Indentificarse) <.. (Registrarse) : <<extends>>
(Pagar) <|-- (Con tarjeta)
(Pagar) <|-- (En efectivo)

@enduml